<Label>:
    font_size: dp(50)
<ScreenManager>:
    Screen:
        name: 'chinese'
        Button:
            id: 1
            text:
            on_press: 
            on_release: app.switchTo('korean')
            font_name: 'Alibaba-PuHuiTi-B'
    Screen:
        name: 'korean'
        Button:
            id: 2
            text:
            on_press: 
            on_release: app.switchTo('chinese')
            font_name: 'NanumGothicCoding-Bold'
            